# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('content', models.CharField(max_length=600)),
                ('topic', models.CharField(max_length=150)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
