# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
