# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170813_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='picture',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
